### ISSUE TITLE
Make inlay hints less visible

### ISSUE THREAD

**Issue by quyykk** [alexdauenhauer/catppuccin-noctis#17]
Thanks for making this theme! I really like it! The only issue I have is that inlay hints look like this:

![image](https://user-images.githubusercontent.com/85879619/212373390-d4e07c9b-717a-43e6-99cb-d483555230a6.png)

they stick out a lot, and it's pretty distracting. Could they be made darker?  like this for example

![image](https://user-images.githubusercontent.com/85879619/212373542-ed5f8864-0493-4759-ad30-50e7423a3a8e.png)

**Comment by alexdauenhauer** [comment]
Great feedback! I'll look into this! I am mostly a python dev so not always fully aware of issues that pop up in other programming languages.

**Comment by alexdauenhauer** [comment]
@quyykk what language is this and can you please provide a code snippet that I can reproduce this on?

**Comment by quyykk** [comment]
This is C++ (with the C/C++ extension - you need to enable inlay hints in the settings; they're not enabled by default). Here's a snippet:

```c++
int add(int first, int second) { return first + second; }

int main()
{
    return add(1, 2);
}
```

**Comment by alexdauenhauer** [comment]
@quyykk I don't think this is a feature I personally use, so I'll let you pick the background color :)

Do you like option1?
<img width="615" alt="image" src="https://user-images.githubusercontent.com/11903445/212571156-73c4e304-6a2f-422e-8c03-eea20b9e7415.png">

or option2?
<img width="622" alt="image" src="https://user-images.githubusercontent.com/11903445/212571193-5586f014-4391-49a5-bfe4-2fe1fb5cbe1c.png">

Do either of these look ok to you? personally I prefer the slightly more subdued version of option 1.

**Comment by alexdauenhauer** [comment]
ok I see why I had set it the way I did. This setting is controlled by `badge.background` and `badge.foreground` which also controls the number bubble here 
<img width="118" alt="image" src="https://user-images.githubusercontent.com/11903445/212571604-16eb6e9c-7420-4bb9-8d6a-7d66b984edff.png">

and I wanted it to be color aligned to the bubbles that show up here 
<img width="40" alt="image" src="https://user-images.githubusercontent.com/11903445/212571625-5e36f443-d50a-40d6-91e4-de133c329f73.png">

But I agree with you that it looks horrible for your use case, so thank you very much for flagging this!

**Comment by quyykk** [comment]
Option 1 looks good to me too! Thanks

> This setting is controlled by badge.background and badge.foreground which also controls the number bubble here

Sounds like something VScode should change :smile:

**Comment by alexdauenhauer** [comment]
Option 1 it is! yeah agreed, it seems like it should be linked to something else (or perhaps there is another setting that I don't know of and it defaults to this when that is unset 🤷 ). If you decide you want to change it to something else later on you can always set this in your settings
```json
"workbench.colorCustomizations": {
  "[Catppuccin Noctis]": {
    "badge.background": "#181825",
    "badge.foreground": "#585b70"
  },
}
```

**Comment by alexdauenhauer** [comment]
resolved in version 1.2.2

**Comment by alexdauenhauer** [comment]
@quyykk hey I found out how to actually control the inlay hints and the badge is just the fallback option. I am thinking of styling the inlay hints like comments based on some feedback I received. What do you think about this look?
![image](https://user-images.githubusercontent.com/11903445/213059320-3ae93834-b69a-446f-88c9-5224e0c7ad46.png)

**Comment by quyykk** [comment]
Yeah that looks good too, thanks!
