### ISSUE TITLE
File renaming transparent background

### ISSUE THREAD

**Issue by chazmcgrill** [alexdauenhauer/catppuccin-noctis#40]
Hi, heres another minor issue I've found:

![image](https://github.com/alexdauenhauer/catppuccin-noctis/assets/24394860/1a6528ac-5765-40a9-98b4-4571310a9171)

File renaming error messages have a transparent background. No idea what the style is for that...

Cheers

**Comment by alexdauenhauer** [comment]
thanks for flagging this @chazmcgrill. fixed in 2.2.1
