### ISSUE TITLE
Change the color style of suggest Widget to make the selected suggestions look more obvious.

### ISSUE THREAD

**Issue by Ninephoenix9** [alexdauenhauer/catppuccin-noctis#56]
Thank you for your great job! The theme is wonderful and I am satisfied with the color.

<img width="1280" alt="image" src="https://github.com/alexdauenhauer/catppuccin-noctis/assets/105162283/57b942c8-a421-4f4f-8ba3-ac6fed88ac13">

However, as you can see, the background color of the selected suggestion line won't change. It's difficult to identify the chosen suggestion. Every line seems identical.

Can you improve it?

**Comment by alexdauenhauer** [comment]
great call! I will try to fix this!

**Comment by alexdauenhauer** [comment]
sorry it took me so long. It should be improved in v3.0.1. Lmk what you think
