### ISSUE TITLE
Weird color when go to define list item background

### ISSUE THREAD

**Issue by HATTER-LONG** [alexdauenhauer/catppuccin-noctis#64]
Hello, thanks for your work, nice theme.

But I meet a weird color when got to define list item, how to change it? thx

<img width="709" alt="image" src="https://github.com/user-attachments/assets/a1f65bed-31da-4117-b0e1-701e37cdde1a">

**Comment by alexdauenhauer** [comment]
what part are you referring to? this gray highlight?
<img width="235" alt="image" src="https://github.com/user-attachments/assets/fc3be819-8d52-4154-82ea-672936739491">

**Comment by alexdauenhauer** [comment]
should be fixed in v3.1.4. let me know if not
